### ISSUE TITLE
Allow conversion from Nullable{T} to T

### ISSUE THREAD

**Issue by KristofferC** [JuliaAttic/Nullables.jl#9]
Moved from https://github.com/JuliaLang/julia/issues/18264
--------------------

Conversion from `NullableArrays` to special array types currently doesn't work very well when converting to a non-`Nullable` element type. This contrasts with standard `Arrays`, for which specific methods are provided. For example, when trying to convert to a sparse matrix:

``` julia
julia> x = NullableArray([1 2])
1×2 NullableArrays.NullableArray{Int64,2}:
 1  2

julia> convert(SparseMatrixCSC{Int,Int}, x)
ERROR: MethodError: Cannot `convert` an object of type Nullable{Int64} to an object of type Int64
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.
 in copy!(::Base.LinearFast, ::Array{Int64,1}, ::Base.LinearFast, ::Array{Nullable{Int64},1}) at ./abstractarray.jl:551
 in convert(::Type{SparseMatrixCSC{Int64,Int64}}, ::NullableArrays.NullableArray{Int64,2}) at ./sparse/sparsematrix.jl:272

```

This could be fixed in Base by defining:

``` julia
Base.convert{T}(::Type{T}, x::Nullable) = convert(T, get(x))
```

This definition makes sense to me, as we already allow conversion _to_ `Nullable`. Of course, null values would trigger a `NullException` just like calling `get` directly.

Cc: `@johnmyleswhite` `@davidagold` `@quinnj`

**Comment by nalimilan** [comment]
Being the original reporter, I don't think we should implement this at this point given that this package is provided for compatibility only.
